"""Type stubs for the fractional-indexing package (no py.typed shipped upstream)."""

BASE_62_DIGITS: str

class FIError(Exception): ...

def generate_key_between(a: str | None, b: str | None, digits: str = ...) -> str: ...
def generate_n_keys_between(a: str | None, b: str | None, n: int, digits: str = ...) -> list[str]: ...
def validate_order_key(key: str, digits: str = ...) -> None: ...
