"""add media_key to summaries.

Revision ID: 428e50631841
Revises: 9fabcc6b8c80
Create Date: 2026-07-09 16:12:29.227718

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "428e50631841"
down_revision: str | Sequence[str] | None = "9fabcc6b8c80"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("summaries", sa.Column("media_key", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("summaries", "media_key")
    # ### end Alembic commands ###
