"""init

Revision ID: 65436f77ed6b
Revises: 
Create Date: 2026-05-15 00:58:23.893073

"""
from collections.abc import Sequence

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65436f77ed6b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("summaries",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("overall_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("action_items",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("summary_id", sa.Uuid(), nullable=False),
    sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("assignee", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column("due_date", sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(["summary_id"], ["summaries.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_action_items_summary_id"), "action_items", ["summary_id"], unique=False)
    op.create_table("decisions",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("summary_id", sa.Uuid(), nullable=False),
    sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("decided_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(["summary_id"], ["summaries.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_decisions_summary_id"), "decisions", ["summary_id"], unique=False)
    op.create_table("topics",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("summary_id", sa.Uuid(), nullable=False),
    sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(["summary_id"], ["summaries.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_topics_summary_id"), "topics", ["summary_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topics_summary_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_decisions_summary_id"), table_name="decisions")
    op.drop_table("decisions")
    op.drop_index(op.f("ix_action_items_summary_id"), table_name="action_items")
    op.drop_table("action_items")
    op.drop_table("summaries")
    # ### end Alembic commands ###
