"""add transcript_segments table.

Revision ID: 7a9fcb6fb2c0
Revises: 2780008cab58
Create Date: 2026-06-30 15:28:01.410987

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a9fcb6fb2c0"
down_revision: str | Sequence[str] | None = "2780008cab58"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("transcript_segments",
    sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column("summary_id", sa.Uuid(), nullable=False),
    sa.Column("speaker_label", sa.String(length=64), nullable=False),
    sa.Column("start_ms", sa.Integer(), nullable=False),
    sa.Column("end_ms", sa.Integer(), nullable=False),
    sa.Column("text", sa.String(), nullable=False),
    sa.ForeignKeyConstraint(["summary_id"], ["summaries.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_transcript_segments_summary_id"), "transcript_segments", ["summary_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transcript_segments_summary_id"), table_name="transcript_segments")
    op.drop_table("transcript_segments")
    # ### end Alembic commands ###
