"""add summary_groups and group_id.

Revision ID: 803a7a025926
Revises: 7a9fcb6fb2c0
Create Date: 2026-06-30 18:40:53.901196

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "803a7a025926"
down_revision: str | Sequence[str] | None = "7a9fcb6fb2c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summary_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_summary_groups_user_name"),
    )
    op.create_index(op.f("ix_summary_groups_user_id"), "summary_groups", ["user_id"], unique=False)
    op.add_column("summaries", sa.Column("group_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_summaries_group_id"), "summaries", ["group_id"], unique=False)
    op.create_foreign_key(
        "fk_summaries_group_id", "summaries", "summary_groups", ["group_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_summaries_group_id", "summaries", type_="foreignkey")
    op.drop_index(op.f("ix_summaries_group_id"), table_name="summaries")
    op.drop_column("summaries", "group_id")
    op.drop_index(op.f("ix_summary_groups_user_id"), table_name="summary_groups")
    op.drop_table("summary_groups")
    # ### end Alembic commands ###
