"""add transcription_jobs.

Revision ID: 9fabcc6b8c80
Revises: 1f63cefa89d9
Create Date: 2026-07-09 13:26:46.884141

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fabcc6b8c80"
down_revision: str | Sequence[str] | None = "1f63cefa89d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("transcription_jobs",
    sa.Column("id", sa.Uuid(), nullable=False),
    sa.Column("user_id", sa.Uuid(), nullable=False),
    sa.Column("status", sa.Enum("pending", "processing", "completed", "failed", name="jobstatus"), nullable=False),
    sa.Column("filename", sa.String(length=255), nullable=False),
    sa.Column("content_hash", sa.String(length=64), nullable=False),
    sa.Column("num_speakers", sa.Integer(), nullable=True),
    sa.Column("audio_key", sa.String(length=255), nullable=True),
    sa.Column("recorded_at", sa.Date(), nullable=True),
    sa.Column("summary_id", sa.Uuid(), nullable=True),
    sa.Column("error", sa.String(), nullable=True),
    sa.Column("attempts", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(["summary_id"], ["summaries.id"], ondelete="SET NULL"),
    sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_transcription_jobs_content_hash"), "transcription_jobs", ["content_hash"], unique=False)
    op.create_index("ix_transcription_jobs_status_created_at", "transcription_jobs", ["status", "created_at"], unique=False)
    op.create_index(op.f("ix_transcription_jobs_summary_id"), "transcription_jobs", ["summary_id"], unique=False)
    op.create_index(op.f("ix_transcription_jobs_user_id"), "transcription_jobs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_transcription_jobs_user_id"), table_name="transcription_jobs")
    op.drop_index(op.f("ix_transcription_jobs_summary_id"), table_name="transcription_jobs")
    op.drop_index("ix_transcription_jobs_status_created_at", table_name="transcription_jobs")
    op.drop_index(op.f("ix_transcription_jobs_content_hash"), table_name="transcription_jobs")
    op.drop_table("transcription_jobs")
    sa.Enum(name="jobstatus").drop(op.get_bind(), checkfirst=True)
